server:
  port: 8083

spring:
  application:
    name: motel-management-service

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      initial-size: 5
      max-size: 15
      max-idle-time: 30m
      max-acquire-time: 3m

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    tracing:
      enabled: false
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: motel-management
      environment: ${SPRING_PROFILES_ACTIVE:docker}

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO
