server:
  port: 8084

spring:
  application:
    name: notification-service
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    username: ubikApp3@gmail.com
    password: mvndhobznradvbba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
